<?php //
//$I = new FunctionalTester($scenario);
//$I->am("guest user");
//$I->wantTo('see page generated by cms');
//
//$I->haveRecord('urls', ['entity_id' => 1, 'entity_type' => 'Lys\Cms\Models\Page', 'path' => '/']);
//$I->haveRecord('pages', ['id' => 1, 'name' => 'home']);
//
//$I->haveRecord('urls', ['entity_id' => 2, 'entity_type' => 'Lys\Cms\Models\Page', 'path' => 'blog']);
//$I->haveRecord('pages', ['id' => 2, 'name' => 'blog']);
//
//$I->amOnPage("/");
//$I->canSeeInTitle('home');
//
//$I->amOnPage('/blog');
//$I->canSeeInTitle('blog');
//
//$I->amOnPage('/this_page_is_no_exist');
//$I->seePageNotFound();